apiVersion: platform.hsdp.io/v1alpha1
kind: SQLInstance
metadata:
  name: test-postgres
  namespace: default
spec:
  parameters:
    engine: postgres
    engineVersion: "14.5"
    storageGB: 10
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
  writeConnectionSecretToRef:
    name: test-postgres-connection

---

apiVersion: v1
data:
  password: Q2hhbmdlTWVCZWZvcmVBY3R1YWxVc2U=
kind: Secret
metadata:
  name: psqlsecret
  namespace: default
type: Opaque


