apiVersion: platform.hsdp.io/v1alpha1
kind: SQLInstance
metadata:
  name: test-postgres
  namespace: default
spec:
  parameters:
    engine: {{ .Values.postgres.engine }}
    engineVersion: "14.5"
    storageGB: {{ .Values.postgres.storageGB }}
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
  writeConnectionSecretToRef:
    name: {{ .Values.postgres.secretName }}

---

apiVersion: v1
data:
  password: Q2hhbmdlTWVCZWZvcmVBY3R1YWxVc2U=
kind: Secret
metadata:
  name: psqlsecret
  namespace: default
type: Opaque


