apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdemoapp
  labels:
    app: springdemoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springdemoapp
  template:
    metadata:
      labels:
        app: springdemoapp
    spec:
      containers:
      - name: springdemoapp
        image: rajshivaram7/springboot-demo-app:latest
        envFrom:
          - secretRef:
              name: test-postgres-connection
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
